#!/usr/bin/env bash
# Configure custom http header
apt-get -y update
apt-get -y install nginx
host=$(cat /etc/hostname)
sed -i "36 i\ \tadd_header X-Served-By $host;\n" /etc/nginx/sites-enabled/default
service nginx restart
