#!/usr/bin/env bash
# Install HAProxy with round robin balancing algorithm
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.6
apt-get -y update
apt-get -y install haproxy=1.6.\*
sed -i "20 i\ \nfrontend my_front\n\tbind *:80\n\tdefault_backend my_back" /etc/haproxy/haproxy.cfg
sed -i "25 i\\backend my_back\n\tbalance roundrobin\n\tmode http\n\tserver 397-web-01 35.196.140.92 check\n\tserver 397-web-02 35.237.19.12 check\n" /etc/haproxy/haproxy.cfg
service haproxy restart
