#!/usr/bin/env bash
# Trapping SIGTERM, SIGINT, SIGQUIT signals
trap "echo Y U no love me?!" SIGINT
trap cleanup SIGQUIT SIGTERM 
cleanup()
{
	echo I hate the kill command
	rm /var/run/holbertonscript.pid
	pkill -f 100-process_and_pid_file -9
}
echo $$ > /var/run/holbertonscript.pid
while true
do
	echo To infinity and beyond
done
