#!/usr/bin/env bash
# Display the time for 12 hrs 59 min
hr=0
min=1
while [ $hr -le 12 ]
do
	echo Hour: $hr
	while [ $min -le 59 ]
	do
		echo $min
		let 'min += 1'
	done
	let 'hr += 1'
	let 'min = 1'
done
