#!/usr/bin/env bash
# Installs a nginx server listening at port 80 w/ custom "home" page
apt-get install -y nginx
service nginx start
echo "Holberton School r0x0rz" > /usr/share/nginx/html/index.html
