#!/usr/bin/env bash
# Installs a nginx server listening at port 80 w/ custom "home" page
apt-get update -y
apt-get install -y nginx
echo "Holberton School for the win!"  > /usr/share/nginx/html/index.html
nginx -g "listen 80;"
service nginx restart
